---
abstract: "It's chained exception module"
author:
  - 'Hiroyoshi Houchi <git@hixi-hyi.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.12.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exception-Chain
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Exception::Chain:
    file: lib/Exception/Chain.pm
    version: 0.01
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/hixi-hyi/p5-Exception-Chain/issues
  homepage: https://github.com/hixi-hyi/p5-Exception-Chain
  repository: git://github.com/hixi-hyi/p5-Exception-Chain.git
version: 0.01
